### ISSUE TITLE
PHP 5.6 compatibility

### ISSUE THREAD

**Issue by poisa** [mopo922/LaravelTreats#3]
Hi there. First off, the `HasCompositePrimaryKey`trait has saved me from a major headache, many thanks for creating this!

Second, is there a reason why this has the php requirement set to 7.0? I don't think I see anything that cannot run in 5.6 but I've only looked in that particular trait. 

I'm currently migrating a project from 5.6 and evaluating this library but would still need to run this under 5.6 for some time before updating to 7.0.

**Comment by mopo922** [comment]
Thanks for the feedback. There are a few places in this project that use the [Null Coalescing Operator](http://php.net/manual/en/migration70.new-features.php#migration70.new-features.null-coalesce-op), which is new in PHP7. I also wanted to do my part to push PHP developers to upgrade to PHP7, as it is a huge performance improvement over PHP5.

**Comment by poisa** [comment]
I see, thanks. 

For now I will just need to modify this a bit in my own codebase as the upgrade doesn't look like it's coming for at least a few months.

**Comment by rafwell** [comment]
+1, force update for php 7 is not a good ideia, once laravel 5.3 is full compatibility with php 5.6.
