### ISSUE TITLE
delete HasCompositePrimaryKey

### ISSUE THREAD

**Issue by isbkch** [mopo922/LaravelTreats#4]
Hi,
I see the methods setKeysForSaveQuery() and find() in the trait, but I was wondering how the delete() would work ? No risk of deleting everything

**Comment by mopo922** [comment]
You can look at the source of `Illuminate\Database\Eloquent\Model` to see that `Model::delete()` calls `Model::performDeleteOnModel()` which calls - tada! - `Model::setKeysForSaveQuery()`.

**Comment by isbkch** [comment]
I should've checked. beautiful

**Comment by mopo922** [comment]
Np. Laravel is such a well-written framework. It makes it easy to override one method like this to adapt it to your needs.
