### ISSUE TITLE
Composite Keys don't work on Pivot Tables

### ISSUE THREAD

**Issue by kmuenkel** [mopo922/LaravelTreats#6]
When attempting to execute a hasManyThrough relationship via a table with a composite key, Laravel attempts to assume the JOIN-ON field to be the primary key assigned to the pivot model.  If the key is an array using your HasCompositePrimaryKey trait, you end up with an "Array to string conversion" error.  This appears to be happening in Model::getQualifiedKeyName() when it calls getKeyName().  That means, just for a start, you'd have to be mindful of all 10 places getQualifiedKeyName gets called, and all 29 places  getKeyName gets called, all currently expecting a string response.

**Comment by mopo922** [comment]
Thanks for the report!

You should be able to get around this issue by specifying the `$localKey` in the 5th parameter of `hasManyThrough()`:

```php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Country extends Model
{
    use \LaravelTreats\Model\Traits\HasCompositePrimaryKey;

    /**
     * The primary key of the table.
     *
     * @var array
     */
    protected $primaryKey = ['country_id', 'continent_id'];

    /**
     * Get all of the posts for the country.
     */
    public function posts()
    {
        return $this->hasManyThrough('App\Post', 'App\User', null, null, 'country_id');
    }
}
```

If someone would like to submit a pull request with a better, more permanent solution I'd love to see it! But I won't be getting around to that any time soon.
