### ISSUE TITLE
php compatibility

### ISSUE THREAD

**Issue by matiasmuller** [mopo922/LaravelTreats#9]
Why is php version 7 required? I work with servers contracted with php 5.6, and for that reason alone I can not install this very practical library through composer.json, and instead, I have included the files manually, and it works well even with that older version of php It is not a serious matter, but if it is necessary to maintain the neat structure of the project, put the oldest version that is supported, unless there is a precise reason why it has been put version 7 as required.

**Comment by mopo922** [comment]
There are some secondary features in this lib that use PHP7 syntax. I'm working on a v2 that strips away a bunch of the stuff that I now realize is not very useful, and when that is ready (won't be soon) I will see if I can lower the PHP version requirement.
